### ISSUE TITLE
Wasm broken: function signature mismatch

### ISSUE THREAD

**Issue by jinu-jang** [tree-sitter/tree-sitter#1095]
I've been building tree-sitters using the following commands.
I'm honestly not sure about the `mkdir deps` part, but I was doing a dumb copy of the code I saw in [dcreager/tree-sitter-test: test.yaml](https://github.com/dcreager/tree-sitter-test/blob/f4c631f53cee49ea0af044f11371001347f1e032/.github/workflows/test.yaml)
```
git clone 'https://github.com/emscripten-core/emsdk.git'
cd emsdk
./emsdk install latest
./emsdk activate latest
cd ..
mkdir deps && cd deps && git clone 'https://github.com/tree-sitter/tree-sitter'
cd tree-sitter
script/build-wasm
cd ../../
npm i tree-sitter-cli web-tree-sitter tree-sitter-javascript
source emsdk/emsdk_env.sh
npx tree-sitter build-wasm node_modules/tree-sitter-javascript
node scripts/testLoadingWasmTreeSitters.js
```

Where `scripts/testLoadingWasmTreeSitters.js` is the exact same as [dcreager/tree-sitter-test: index.js](https://github.com/dcreager/tree-sitter-test/blob/master/index.js)

However, for at least Javascript, Typescript, Python, C++, and Java, I get the following error
Am I building something incorrectly or is this something related to #1088 ?
```
RuntimeError: function signature mismatch
    at <anonymous>:wasm-function[80]:0x16cb7
    at <anonymous>:wasm-function[131]:0x26333
    at ts_parser_parse_wasm (<anonymous>:wasm-function[243]:0x2d8fd)
    at Object.Module._ts_parser_parse_wasm (C:\src\PythiaCompose\node_modules\web-tree-sitter\tree-sitter.js:1:18760)
    at Parser.parse (C:\src\PythiaCompose\node_modules\web-tree-sitter\tree-sitter.js:1:33876)
    at C:\src\PythiaCompose\scripts\testLoadingWasmTreeSitters.js:14:10
```

**Comment by dcreager** [comment]
Hi @jinu-jang!  Yes, I think this is the same issue as #1088.  We fixed that in #1089, but haven't cut a new release of `web-tree-sitter` yet with the fix.  I see that you're doing a `git clone` to get the latest copy of tree-sitter (which should have the fix).  But I think your `npm install` command then grabs a versioned copy of `web-tree-sitter` from npm instead of using your clone.  I'm not _entirely_ sure I've got the syntax right, but I think you want that step to be:

```
npm i tree-sitter-cli deps/tree-sitter/lib/binding_web tree-sitter-javascript
```

**Comment by dcreager** [comment]
@maxbrunsfeld :+1: I'll give it a shot!

**Comment by jinu-jang** [comment]
Yup I saw the npm get updated just now as well so I'm trying it out right now!
I'll let yall know how it goes

**Comment by jinu-jang** [comment]
Alright thank y'all I think it works now!
Y'all are the best <3
