### ISSUE TITLE
YAML doesn't work in the playground

### ISSUE THREAD

**Issue by Timmmm** [tree-sitter/tree-sitter#1116]
If I try to select YAML in the playground it just jumps back to the previous selection and I get this error in the log:

```
LinkError: WebAssembly.instantiate(): Import #15 module="env" function="table" error: table import requires a WebAssembly.Table
handleLanguageChange @ playground.js:90
async function (async)
handleLanguageChange @ playground.js:88
```

I tried every other language and they all work except YAML.

(Classic YAML, infecting everything else with its awfulness!)

**Comment by milahu** [comment]
workaround: https://ikatyang.github.io/tree-sitter-yaml/

**Comment by RedCMD** [comment]
I get this error instead:
```
tree-sitter.js:1 Uncaught (in promise) TypeError: _ is not a function
    at e.<computed> (tree-sitter.js:1:14963)
    at 000b176e:0x18a0
    at tree-sitter.wasm:0x2444a
    at Parser.parse (tree-sitter.js:1:49285)
    at handleCodeChange (playground.js:113:28)
    at HTMLSelectElement.handleLanguageChange (playground.js:99:5)
```
