### ISSUE TITLE
Incompatible language version

### ISSUE THREAD

**Issue by banacorn** [tree-sitter/tree-sitter#151]
I'm getting errors like this when loading the grammar.

`RangeError: Incompatible language version. Expected 5. Got 6`

After some digging, I found that there's a line generated in `src/parser.c`:
```
#define LANGUAGE_VERSION 6
```
I was able to remedy the problem by overwriting the LANGUAGE_VERSION from 6 to 5 by hand every time I rebuild the package.

However, the version has bumped to 7 at the time of writing.
https://github.com/tree-sitter/tree-sitter/blame/84b15d2c782331352952a3e67adbb815c99b9d11/include/tree_sitter/runtime.h#L12

Should I be using a specific version of `tree-sitter-cli` (hence `tree-sitter-cli`) when developing my tree-sitter grammar to avoid this conflict?

The complete stack:
```
/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:587 Failed to load grammar: /Users/banacorn/.atom/dev/packages/language-agda/grammars/tree-sitter-agda.cson RangeError: Incompatible language version. Expected 5. Got 6
    at new TreeSitterLanguageMode (/Applications/Atom.app/Contents/Resources/app.asar/src/tree-sitter-language-mode.js:18:19)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/Applications/Atom.app/Contents/Resources/app.asar/src/grammar-registry.js:165:14)
    at grammarScoresByBuffer.forEach (/Applications/Atom.app/Contents/Resources/app.asar/src/grammar-registry.js:354:39)
    at Map.forEach (native)
    at GrammarRegistry.grammarAddedOrUpdated (/Applications/Atom.app/Contents/Resources/app.asar/src/grammar-registry.js:336:32)
    at GrammarRegistry.addGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/grammar-registry.js:406:12)
    at TreeSitterGrammar.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/tree-sitter-grammar.js:66:39)
    at Package.loadGrammarsSync (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:585:17)
    at Workspace.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:359:13)
    at AtomEnvironment.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1241:41)
    at <anonymous>
```

The version of Atom I'm using:
```
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by thomasjo** [comment]
Pretty sure you should use a compatible version of tree-sitter, which means same (semantic) version range as Atom's tree-sitter version. As of writing this, Atom is bundled with tree-sitter 0.9.2, so you should stick to the 0.9.x range for now.

**Comment by banacorn** [comment]
Thank you!
