### ISSUE TITLE
Push `tree-sitter` version 0.20.4 to npm

### ISSUE THREAD

**Issue by alex-pinkus** [tree-sitter/tree-sitter#1628]
The [`npm` package `tree-sitter`](https://www.npmjs.com/package/tree-sitter) doesn't yet have an ABI-14-compatible version published--its latest version is 0.20.0. If, let's say, [someone were to publish](https://github.com/alex-pinkus/tree-sitter-swift/pull/104) a grammar that's explicitly compiled with `--abi 14`, anyone trying to depend on it from NPM would get a message like:

```
/home/runner/work/tree-sitter-swift/tree-sitter-swift/test-npm-package/node_modules/tree-sitter/index.js:259
  setLanguage.call(this, language);
              ^

RangeError: Incompatible language version. Compatible range: 13 - 13. Got: 14
    at Parser.setLanguage (/home/runner/work/tree-sitter-swift/tree-sitter-swift/test-npm-package/node_modules/tree-sitter/index.js:259:15)
    at Object.<anonymous> (/home/runner/work/tree-sitter-swift/tree-sitter-swift/test-npm-package/index.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

There has been a `0.20.4` published for `tree-sitter-cli`, but unless I'm missing something, we need to update the library too.

**Comment by ahelwer** [comment]
Ref https://github.com/tree-sitter/tree-sitter/issues/1223

**Comment by verhovsky** [comment]
This should be fixed by node-tree-sitter (simply "tree-sitter" on npm) version 0.20.3

https://github.com/tree-sitter/node-tree-sitter/pull/146
