### ISSUE TITLE
Test failure on s390x

### ISSUE THREAD

**Issue by alebastr** [tree-sitter/tree-sitter#1693]
(Depends on #1692)
There's one test that is still failing on s390x - `tests::query_test::test_query_is_pattern_guaranteed_at_step`. My best guess is that it's a more subtle issue caused by a different endianness.

<details>
<summary>Log and backtrace</summary>

```
$ cargo test -- tests::query_test::test_query_is_pattern_guaranteed_at_step
    Finished test [unoptimized + debuginfo] target(s) in 1.32s
     Running unittests (target/debug/deps/tree_sitter_cli-b76c8a7956d5e7b0)

running 1 test
test tests::query_test::test_query_is_pattern_guaranteed_at_step ... FAILED

failures:

---- tests::query_test::test_query_is_pattern_guaranteed_at_step stdout ----

  query example: "no guaranteed steps"
  query example: "all guaranteed steps"
  query example: "a fallible step that is optional"
  query example: "multiple fallible steps that are optional"
  query example: "guaranteed step after fallibe step"
  query example: "fallible step in between two guaranteed steps"
  query example: "one guaranteed step after a repetition"
  query example: "guaranteed steps after multiple repetitions"
  query example: "a guaranteed step with a field"
  query example: "multiple guaranteed steps with fields"
  query example: "nesting, one guaranteed step"
  query example: "a guaranteed step after some deeply nested hidden nodes"
  query example: "nesting, no guaranteed steps"
  query example: "a guaranteed step after a nested node"
  query example: "a step that is fallible due to a predicate"
thread 'tests::query_test::test_query_is_pattern_guaranteed_at_step' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: Description: a step that is fallible due to a predicate, Pattern: "(subscript_expression object: (member_expression object: (identifier) @obj property: (property_identifier) @prop) \"[\" (#match? @prop \"foo\"))", substring: "property_identifier", expected is_definite to be false', cli/src/tests/query_test.rs:3843:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:154:5
   4: tree_sitter_cli::tests::query_test::test_query_is_pattern_guaranteed_at_step::{{closure}}
             at ./src/tests/query_test.rs:3843:17
   5: tree_sitter_cli::tests::helpers::allocations::record
             at ./src/tests/helpers/allocations.rs:50:17
   6: tree_sitter_cli::tests::query_test::test_query_is_pattern_guaranteed_at_step
             at ./src/tests/query_test.rs:3830:5
   7: tree_sitter_cli::tests::query_test::test_query_is_pattern_guaranteed_at_step::{{closure}}
             at ./src/tests/query_test.rs:3557:1
   8: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

I have a Fedora/s390x VM with dev environment, but sadly I haven't found enough free time to figure out how the specific parts of the code supposed to work.
I'll be happy to debug or test any ideas for the fix though.

**Comment by amaanq** [comment]
It's fixed now! Read more about the issue here that affected all big endian machines: https://github.com/tree-sitter/tree-sitter/pull/2402
