### ISSUE TITLE
Invalid URL error with web-tree-sitter

### ISSUE THREAD

**Issue by wenkokke** [tree-sitter/tree-sitter#1802]
With `web-tree-sitter` version `0.20.5`, calling `Parser.init` is failing with an Invalid URL error:
```
(node:81433) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:225:11)
    at fetch (node:internal/bootstrap/pre_execution:196:5)
    at tree-sitter-talon/node_modules/web-tree-sitter/tree-sitter.js:1:15192
    at tree-sitter-talon/node_modules/web-tree-sitter/tree-sitter.js:1:15413
    at new Promise (<anonymous>)
    at Parser.init (tree-sitter-talon/node_modules/web-tree-sitter/tree-sitter.js:1:332)
    at Object.<anonymous> (tree-sitter-talon/script/tree-sitter-parse.js:13:8)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
node:internal/deps/undici/undici:4832
            throw new TypeError("Failed to parse URL from " + input, { cause: err });
                  ^

TypeError: Failed to parse URL from tree-sitter-talon/node_modules/web-tree-sitter/tree-sitter.wasm
    at new Request (node:internal/deps/undici/undici:4832:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:5524:29)
    ... 4 lines matching cause stack trace ...
    at new Promise (<anonymous>)
    at Parser.init (tree-sitter-talon/node_modules/web-tree-sitter/tree-sitter.js:1:332)
    at Object.<anonymous> (tree-sitter-talon/script/tree-sitter-parse.js:13:8)
    at Module._compile (node:internal/modules/cjs/loader:1112:14) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:388:5)
      at URL.onParseError (node:internal/url:564:9)
      at new URL (node:internal/url:644:5)
      at new Request (node:internal/deps/undici/undici:4830:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:5524:29)
      at Object.fetch (node:internal/deps/undici/undici:6351:20)
      at fetch (node:internal/bootstrap/pre_execution:197:25)
      at tree-sitter-talon/node_modules/web-tree-sitter/tree-sitter.js:1:15192
      at tree-sitter-talon/node_modules/web-tree-sitter/tree-sitter.js:1:15413
      at new Promise (<anonymous>) {
    input: 'tree-sitter-talon/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.5.0
```

**Comment by wenkokke** [comment]
The code I'm running is:
```javascript
#!/usr/bin/env node --trace-warnings --unhandled-rejections=strict

const fs = require('fs');
const path = require('path');
const Parser = require('web-tree-sitter');
const tree_sitter_talon_wasm = path.resolve(__dirname, '..', 'tree-sitter-talon.wasm');

if (process.argv.length < 3) {
  console.log('Usage: script/tree-sitter-parse.js <file..>')
  process.exit(1)
}

Parser.init().then(() => {
  Parser.Language.load(tree_sitter_talon_wasm).then((Talon) => {
    const parser = new Parser;
    parser.setLanguage(Talon);
    for (let i = 2; i < process.argv.length - 1; i++) {
      const fileName = process.argv[i]
      const sourceCode = fs.readFileSync(fileName, 'utf8')
      const tree = parser.parse(sourceCode);
    }
  });
});
```

**Comment by J3RN** [comment]
This appears to be the same issue as #1765
