### ISSUE TITLE
web-tree-sitter doesn't seem to work in node.js on Windows

### ISSUE THREAD

**Issue by TylerLeonhardt** [tree-sitter/tree-sitter#1978]
Basic script running in node.js v16:
```js
const path = require('path');
const Parser = require('web-tree-sitter');

(async () => {
    await Parser.init();
    const parser = new Parser();
    const Lang = await Parser.Language.load(path.join(__dirname, 'tree-sitter-typescript.wasm'));
    parser.setLanguage(Lang);
    const tree = parser.parse('let x = 1;');
    console.log(tree.rootNode.toString());
})();
```

> I had built the `tree-sitter-typescript.wasm` in ubuntu ([in a GH Action](https://github.com/microsoft/vscode-l10n/actions/runs/3617478590/jobs/6096381430)) and copied it over to the Windows build.

Throws the following:
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:748:3)
    at tryReadSync (node:fs:448:20)
    at Object.readFileSync (node:fs:494:19)
    at Language.load (D:\a\vscode-l10n\vscode-l10n\l10n-dev\node_modules\web-tree-sitter\tree-sitter.js:1:50182)
    at D:\a\vscode-l10n\vscode-l10n\l10n-dev\test.js:22:40 {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
```

Seems to totally work fine on the Linux side and in macOS (run locally).

**Comment by TylerLeonhardt** [comment]
Nevermind... my own fail using the `download-artifact` action.
