### ISSUE TITLE
node-gyp on macOs 10.14 Mojave

### ISSUE THREAD

**Issue by banacorn** [tree-sitter/tree-sitter#203]
There seems to be an [epidemic of `node-gyp`](https://github.com/nodejs/node-gyp/issues/569#issuecomment-423289225) on macOs 10.14 Mojave.

The version of `node-gyp` that Atom is using is too old.

Packages with tree-sitter grammar cannot be installed or upgraded at all!

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
```

Here are 2 copies of complete error log from different people:
* https://gist.github.com/banacorn/0b10f5a029ae10d7cf9e81d5baed90f7
* https://gist.github.com/psygnisfive/06e3e9802011035db6f38d08045293fc

Maybe we should consider switching from `node-gyp` to a modern and maintained alternative #175.

**Comment by maxbrunsfeld** [comment]
Unfortunately, there is no modern and maintained alternative which does not have the same problem of assuming that the user has other software installed on their machine already, as discussed in #175.

But I don’t think these errors are Mojave specific. The same errors happen on previous macOS versions if you don’t have XCode installed.

The best solution is to do what we did for tree-sitter-ruby and tree-sitter-bash: use prebuild to build the libraries ahead of time on CI so that the end user doesn’t have to build anything.

I’m on mobile right now so it’s hard to grab links, but check out the PRs that add prebuild support in those repos.

**Comment by banacorn** [comment]
I see!

I've sent a request to install AppVeyor on [tree-sitter-agda](https://github.com/tree-sitter/tree-sitter-agda), could you turn it on for me? Thanks!!

**Comment by banacorn** [comment]
Where can I get enrypted tokens like [this](https://github.com/tree-sitter/tree-sitter-bash/commit/56805a357ff03e5fa67eded11ab8ac06e857fac8) for prebuild uploads on Travis and Appveyor?

**Comment by maxbrunsfeld** [comment]
@banacorn You now have admin privileges on this repo (I thought you did already, but apparently not; sorry about that).

I think you should be able to set up Appveyor and prebuilding with your own credentials. As far as I can remember, the steps are:

* Generate a personal [GitHub API token](https://github.com/settings/tokens)
* Encrypt the token for Travis-CI [with the `travis` gem](https://docs.travis-ci.com/user/encryption-keys/#usage)
* Encrypt the token for appveyor [with their online tool](https://www.appveyor.com/docs/build-configuration/#secure-variables)
* Add the `prebuild` module as a `devDependency` of `tree-sitter-agda` 
* Modify your `.travis.yml` and `appveyor.yml` similarly to https://github.com/tree-sitter/tree-sitter-ruby/pull/87

**Comment by banacorn** [comment]
For future Googlers:

* Encrypt the token Travis-CI with the environment variable `PREBUILD_UPLOAD`
```
travis encrypt PREBUILD_UPLOAD="... your personal GitHub API token here ..." --add
```
