### ISSUE TITLE
Indicate in engines field that node 8 is required

### ISSUE THREAD

**Issue by aryairani** [tree-sitter/tree-sitter#205]
Just as a heads up: I got this error when following the tutorial instructions:

```
$ tree-sitter generate
/Users/arya/opensource/unison/editor-support/tree-sitter-unison/node_modules/tree-sitter-cli/lib/cli/helpers/profile-command.js:7
async function profileCommand (command, containingFunctionName, callback) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at generate (/Users/arya/opensource/unison/editor-support/tree-sitter-unison/node_modules/tree-sitter-cli/lib/cli/generate.js:8:26)
    at Object.<anonymous> (/Users/arya/opensource/unison/editor-support/tree-sitter-unison/node_modules/tree-sitter-cli/cli.js:36:34)
```

I upgraded npm to 10.11.0 and with some additional rebuild effort, it worked fine

**Comment by maxbrunsfeld** [comment]
Yeah, we should indicate in the ‘engines’ field that node 8 or later is required.

**Comment by maxbrunsfeld** [comment]
I don't think we need to restrict the node version now that the CLI has been implemented in Rust (see https://github.com/tree-sitter/tree-sitter/pull/260). You can use whatever version of node is capable of parsing your own `grammar.js` file.
