### ISSUE TITLE
Cannot load web-tree-sitter in nodejs due to `fetch` error INVALID_URL

### ISSUE THREAD

**Issue by HALOCORE** [tree-sitter/tree-sitter#2087]
I am following the exact steps in document about web-tree-sitter to use it in nodejs.

I installed web-tree-sitter inside a folder `home/xxxx/tree_sitter/` using `npm install web-tree-sitter` and then create a script `tree_sitter_try.js` with the following content:

```js
const Parser = require('web-tree-sitter');
Parser.init().catch(err => console.error(err));

//Parser.init().then(async () => {
    //const parser = new Parser;
    //const JavaScript = await Parser.Language.load('./parser-wasms/tree-sitter-javascript.wasm');
    //parser.setLanguage(JavaScript);
    
    //const sourceCode = 'let x = 1; console.log(x);';
    //const tree = parser.parse(sourceCode);
    //console.log(tree.rootNode.toString());
});
```

When executing the script, the `require` fails. it says that `tree-sitter.js` failed to fetch `tree-sitter.wasm` due to invalid URL:
```
$ node tree_sitter_query.js 
node:internal/deps/undici/undici:11404
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /home/xxxx/tree_sitter/node_modules/web-tree-sitter/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11404:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:6996:25)
      at fetch2 (node:internal/deps/undici/undici:10545:25)
      at Object.fetch (node:internal/deps/undici/undici:11402:18)
      at fetch (node:internal/process/pre_execution:237:25)
      at /home/xxxx/tree_sitter/node_modules/web-tree-sitter/tree-sitter.js:1:18418
      at /home/xxxx/tree_sitter/node_modules/web-tree-sitter/tree-sitter.js:1:18639
      at new Promise (<anonymous>) {
    input: '/home/xxxx/tree_sitter/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.14.1
```

It seems the local file path is considered as INVALID_URL. May I ask how to load web-tree-sitter in nodejs? Thanks!

**Comment by sogaiu** [comment]
FWIW, your script (with the addition of the change of commenting the last line) worked here when I tried Node.js versions:

* 12.22.12
* 14.21.1
* 16.19.0

but not 18.12.1

It looks like you tried 18.14.1, so may be it has something to do with the 18.x series?

**Comment by HALOCORE** [comment]
Thank you! It works on v16.19 indeed. (below is the result after uncomment the rest of the script)
```sh
$ node tree_sitter_try.js 
(program (lexical_declaration (variable_declarator name: (identifier) value: (number))) (expression_statement (call_expression function: (member_expression object: (identifier) property: (property_identifier)) arguments: (arguments (identifier)))))
$ node --version
v16.19.1
```
