### ISSUE TITLE
Failed to load grammar (DLL initialization routine failed)

### ISSUE THREAD

**Issue by misode** [tree-sitter/tree-sitter#263]
I am trying to make an Atom package that uses the tree-sitter-mcfunction module that I'm working on. When testing that tree-sitter module, things are looking ok, but when I try to use that module in the atom package mcfunction-plus, it gives this weird error and I can't seem to fix it.

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: [mcfunction-plus](https://github.com/misode/mcfunction-plus) package 0.0.2

### Stack Trace

Failed to load a mcfunction-plus package grammar

```
At A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\misoloo\.atom\packages\mcfunction-plus\node_modules\tree-sitter-mcfunction\build\Release\tree_sitter_mcfunction_binding.node in C:\Users\misoloo\.atom\packages\mcfunction-plus\grammars\tree-sitter-mcfunction.cson

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\misoloo\.atom\packages\mcfunction-plus\node_modules\tree-sitter-mcfunction\build\Release\tree_sitter_mcfunction_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:145974)
    at /packages/mcfunction-plus/node_modules/tree-sitter-mcfunction/index.js:2:20)
    at /packages/mcfunction-plus/node_modules/tree-sitter-mcfunction/index.js:11:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:1:639369)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:2952362)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:360476)
    at l.readFile (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:360317)
    at ~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:581103
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
  at /packages/mcfunction-plus/grammars/tree-sitter-mcfunction.cson:1:1
```

### Commands

```
  3x -0:25.8.0 editor:newline (input.hidden-input)
     -0:19.5.0 autocomplete-plus:confirm (input.hidden-input)
     -0:18.4.0 editor:delete-to-beginning-of-word (input.hidden-input)
 12x -0:17.5.0 core:backspace (input.hidden-input)
     -0:15.1.0 editor:newline (input.hidden-input)
     -0:14.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
auto-indent 0.5.0 
charcode-display 0.2.1 
ftp-remote-edit 0.12.19 
Hydrogen undefined 
mcfunction 0.6.4 
mcfunction-plus 0.0.2 
open-on-bitbucket 0.5.0 
remote-ftp 2.2.2 
remote-sync 4.1.8 
Sublime-Style-Column-Selection 1.7.5 
teletype 0.13.3 
terminal-plus 0.14.5 
```

**Comment by maxbrunsfeld** [comment]
I think this means that your binary was built for the wrong version of V8, or the wrong architecture. Maybe you built it to work with your local `node`, not Atom's version of Electron? Did you try running `apm rebuild`?

See also https://electronjs.org/docs/tutorial/using-native-node-modules.

**Comment by misode** [comment]
@maxbrunsfeld I'm not really sure what you mean. Why would the node version of Atom be different and how can I use that one instead?
>Did you try running apm rebuild?

Is this for the parser or for the grammar? I'd assume the grammar but that didn't fix it.

**Comment by misode** [comment]
Update: `apm rebuild` failed in git bash, but worked successfully in cmd.exe 🎉 

![mintty_2019-05-11_23-00-12](https://user-images.githubusercontent.com/17352009/57574940-c8ad2f00-7441-11e9-9a18-a6ee40539043.png)
