### ISSUE TITLE
Possible bug with incremental `parse()`-ing combined with the cursor API

### ISSUE THREAD

**Issue by DavisVaughan** [tree-sitter/tree-sitter#2766]
I've been debugging a crash related to the cursor API, and I _think_ I've determined that it has to do with incremental parsing not updating the tree in a way that works well with the cursor API. 

This branch has a failing tree-sitter test that demonstrates the issue:
https://github.com/DavisVaughan/tree-sitter/commit/2c7056b17679e2193c6aca44e98e1bc7787dd49e

The only tip I can give from poking around is that it looks like the child counts are wrong in some cases (I'm not really sure though)

```rust
let text = "// hi there";

// One pass parsing works fine
let tree = parser.parse(text, None).unwrap();

let mut cursor = tree.walk();
assert_eq!(cursor.node().kind(), "source_file");

assert!(cursor.goto_first_child());
assert_eq!(cursor.node().kind(), "line_comment");
assert_eq!(cursor.node().utf8_text(text.as_bytes()).unwrap(), text);

// Incremental parsing fails
let tree = parser.parse("", None).unwrap();
let tree = parser.parse("//", Some(&tree)).unwrap();
let tree = parser.parse(text, Some(&tree)).unwrap();

let mut cursor = tree.walk();
assert_eq!(cursor.node().kind(), "source_file");

// In particular, assertion fails here!
assert!(cursor.goto_first_child());
assert_eq!(cursor.node().kind(), "line_comment");
assert_eq!(cursor.node().utf8_text(text.as_bytes()).unwrap(), text);
```

Fails for me with:

```rust
running 1 test
thread 'tests::tree_test::test_tree_cursor' panicked at 'assertion failed: cursor.goto_first_child()', cli/src/tests/tree_test.rs:398:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: tree_sitter_cli::tests::tree_test::test_tree_cursor
             at ./src/tests/tree_test.rs:398:5
   4: tree_sitter_cli::tests::tree_test::test_tree_cursor::{{closure}}
             at ./src/tests/tree_test.rs:301:23
   5: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::tree_test::test_tree_cursor ... FAILED

failures:

failures:
    tests::tree_test::test_tree_cursor

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 264 filtered out; finished in 0.06s

error: test failed, to rerun pass `-p tree-sitter-cli --lib`
```

**Comment by maxbrunsfeld** [comment]
I think this is a misuse of the incremental parsing API. If you're going to pass in an old tree (in order to reuse parts of it), but with different source code, you need to call `.edit` on the old tree in the edited locations, so that the old tree is in a consistent state with the new source code. There's some docs about this [here](https://tree-sitter.github.io/tree-sitter/using-parsers#editing).

**Comment by DavisVaughan** [comment]
Oh you're totally right. My bad, I ended up coming up with this example while trying to make a minimal reproducible example for https://github.com/tree-sitter/tree-sitter/issues/2767, which is my real problem. In the process I totally forgot about `edit()`, sorry about that!
