### ISSUE TITLE
The module '.../tree_sitter_runtime_binding.node' was compiled against a different Node.js version error?

### ISSUE THREAD

**Issue by lancejpollard** [tree-sitter/tree-sitter#2867]
I just installed `tree-sitter`, `tree-sitter-javascript`, and `tree-sitter-swift`, and played with it for an hour. Now a few hours later, I try running some TypeScript code with `tsx` like normal (loading the tree-sitter stuff), and I get this:

```
node:internal/modules/cjs/loader:1452
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/Users/lancepollard/start/termsurf/deck/task/node_modules/.pnpm/tree-sitter@0.20.6/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1452:18)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/lancepollard/start/termsurf/deck/task/node_modules/.pnpm/tree-sitter@0.20.6/node_modules/tree-sitter/index.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/Users/lancepollard/Library/pnpm/global/5/.pnpm/tsx@4.7.0/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.19.0
```

So I ran `pnpm install` again and It succeeded, but then trying to run my code again it failed again with the same error:

```
(base) $ pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +765
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
node_modules/.pnpm/tree-sitter-javascript@0.20.1/node_modules/tree-sitter-javascript: Running install script, done in 2.1s
node_modules/.pnpm/tree-sitter@0.20.6/node_modules/tree-sitter: Running install script, done in 161ms
node_modules/.pnpm/tree-sitter-cli@0.20.6/node_modules/tree-sitter-cli: Running install script, done in 30.3s
node_modules/.pnpm/tree-sitter-swift@0.3.6/node_modules/tree-sitter-swift: Running install script, done in 18s
node_modules/.pnpm/esbuild@0.19.11/node_modules/esbuild: Running postinstall script, done in 223ms
node_modules/.pnpm/tree-sitter-swift@0.3.6/node_modules/tree-sitter-swift: Running postinstall script, done in 2.2s
node_modules/.pnpm/puppeteer@3.3.0/node_modules/puppeteer: Running install script, done in 75ms
node_modules/.pnpm/puppeteer@21.7.0_typescript@5.3.3/node_modules/puppeteer: Running postinstall script, done in 172ms
Done in 51.5s
(base) $ tsx code/cli tmp/test.js
node:internal/modules/cjs/loader:1452
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/Users/lancepollard/start/termsurf/deck/task/node_modules/.pnpm/tree-sitter@0.20.6/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1452:18)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/lancepollard/start/termsurf/deck/task/node_modules/.pnpm/tree-sitter@0.20.6/node_modules/tree-sitter/index.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (/Users/lancepollard/Library/pnpm/global/5/.pnpm/tsx@4.7.0/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.19.0
```

For some reason it is saying `Node.js v18.19.0` right there, but then I run this and get Node.js v20.10:

```
$ node -v
v20.10.0
```

Same terminal window, the next command. Any ideas what might be happening?

**Comment by ObserverOfTime** [comment]
This shouldn't be happening anymore since Node bindings switched to N-API.
