### ISSUE TITLE
cursor.currentNode() doesn't work on MISSING nodes

### ISSUE THREAD

**Issue by verhovsky** [tree-sitter/tree-sitter#2874]
If your tree contains MISSING nodes and you try to walk it depth-first you'll get this error:

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at yt (tree-sitter.js:1:50378)
    at currentNode (tree-sitter.js:1:41832)
    at traverseTree (<anonymous>:10:21)
    at traverseTree.next (<anonymous>)
    at <anonymous>:2:5
```

To reproduce, go to https://tree-sitter.github.io/tree-sitter/playground select "Bash" and then paste this code into the browser console:

```js
await TreeSitter.init();
const Bash = await TreeSitter.Language.load("/tree-sitter-bash.wasm");
const parser = new TreeSitter();
parser.setLanguage(Bash);

function* traverseTree(tree) {
  const cursor = tree.walk();

  let reachedRoot = false;
  while (!reachedRoot) {
    let currentNode = cursor.currentNode;
    // TreeCursor.currentNode is a property in Node but a function in the browser
    // https://github.com/tree-sitter/tree-sitter/issues/2195
    if (typeof currentNode === "function") {
      currentNode = currentNode();
    }
    yield currentNode;

    if (cursor.gotoFirstChild()) {
      continue;
    }

    if (cursor.gotoNextSibling()) {
      continue;
    }

    let retracing = true;
    while (retracing) {
      if (!cursor.gotoParent()) {
        retracing = false;
        reachedRoot = true;
      }

      if (cursor.gotoNextSibling()) {
        retracing = false;
      }
    }
  }
}

const bashCodeWithMissingQuote = 'curl "';
[...traverseTree(parser.parse(bashCodeWithMissingQuote))];
```

`curl "` is parsed like this:

```
program [0, 0] - [1, 0]
  command [0, 0] - [1, 0]
    name: command_name [0, 0] - [0, 4]
      word [0, 0] - [0, 4]
    argument: string [0, 5] - [1, 0]
      MISSING " [1, 0] - [1, 0]
```

**Comment by amaanq** [comment]
I think it's fine now, seems to be potentially related to the zero width parent bug I fixed in #3191
