### ISSUE TITLE
wasm memory out of bounds

### ISSUE THREAD

**Issue by jeff-hykin** [tree-sitter/tree-sitter#337]
I'm working with @EvgeniyPeshkov and @georgewfraser to try to get tree sitter support on VS Code. I'm using wasm for cross platform since the code needs to be compiled before the extension is published.

The repo with the error is [here](https://github.com/jeff-hykin/tree-sitter), the relevant file is `src/extension.ts`

To get the `wasm` file for c++, I cloned `tree-sitter-cpp` and then ran 
```
npm install
tree-sitter generate
tree-sitter build-wasm
```
And then I copied and pasted the wasm file into the repo I'm working on. (I'm not sure if there is anything else I needed to copy like a javascript file).

The repo currently works using node-gyp (see `EvgeniyPeshkov/syntax-highlighter`), but switching to the wasm version gets this error when loading:

```
[Extension Host] Here is the error stack:  RuntimeError: memory access out of bounds
	at wasm-function[89]:3
	at wasm-function[880]:225
	at wasm-function[819]:209
	at Object.Module._ts_parser_parse_wasm (/Users/jeffhykin/Nextcloud/Programming/syntax-highlighter/node_modules/web-tree-sitter/tree-sitter.js:1:38206)
	at Parser.parse (/Users/jeffhykin/Nextcloud/Programming/syntax-highlighter/node_modules/web-tree-sitter/tree-sitter.js:1:47586)
	at /Users/jeffhykin/Nextcloud/Programming/syntax-highlighter/out/extension.js:193:52
	at Generator.next (<anonymous>)
	at __awaiter (/Users/jeffhykin/Nextcloud/Programming/syntax-highlighter/out/extension.js:7:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/jeffhykin/Nextcloud/Programming/syntax-highlighter/out/extension.js:3:12)
	at initTree (/Users/jeffhykin/Nextcloud/Programming/syntax-highlighter/out/extension.js:182:20)
	at /Users/jeffhykin/Nextcloud/Programming/syntax-highlighter/out/extension.js:211:19
	at Generator.next (<anonymous>)
	at __awaiter (/Users/jeffhykin/Nextcloud/Programming/syntax-highlighter/out/extension.js:7:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/jeffhykin/Nextcloud/Programming/syntax-highlighter/out/extension.js:3:12)
	at activate (/Users/jeffhykin/Nextcloud/Programming/syntax-highlighter/out/extension.js:64:12)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:731:936)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:731:625)
	at define._doActivateExtension.Promise.all.then.e (/Applications/Visual Studio 
```

I'm not sure if this is my fault or a web-tree-sitter issue. I tried web-tree-sitter `0.15.2` and `0.15.1`.

**Comment by maxbrunsfeld** [comment]
Hmm, I'm not sure what's causing that. Can you reproduce the error by parsing the same C++ code in [the online playground](https://tree-sitter.github.io/tree-sitter/playground)? If so, can you determine the smallest program fragment that causes the problem?

If not, could you put together a single JS file that exhibits the problem?

**Comment by jeff-hykin** [comment]
I'll get a js file. It's failing on load, an empty C++ file fails, and a hello world C++ file also fails.

**Comment by jeff-hykin** [comment]
Well in theory this is all that would be needed to reproduce the problem:
```
const Parser = require("web-tree-sitter")
(async ()=>{
    let parser = new Parser()
    await Parser.init()
    languageObj = await Parser.Language.load(`../language-parsers/cpp.wasm`)
    parser.setLanguage(languageObj)
    tree = parser.parse(`
    int main() {
        return 1;
    }
    `)
})()
```

However I'm running into some other very strange issues along the way.
I'm using npm `v6.7.0` and node `v11.11.0`

This code causes an error
```
const Parser = require("web-tree-sitter")
(async ()=>{})
```
```
TypeError: Class constructor Parser cannot be invoked without 'new'
    at Object.<anonymous> (/Users/jeffhykin/Nextcloud/Programming/tree-sitter/out/test.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```

However this code
```
const Parser = require("web-tree-sitter")
async ()=>{}
```
And this code
```
const Parser = require("web-tree-sitter")
let func = async ()=>{
}
func()
```
Do not cause errors


However 
```
const Parser = require("web-tree-sitter")
let func = async ()=>{
    let parser = new Parser()
}
func()
```
Causes a different error
```
TypeError: Cannot read property 'apply' of undefined
    at Object.Module._ts_parser_new_wasm (/Users/jeffhykin/Nextcloud/Programming/tree-sitter/node_modules/web-tree-sitter/tree-sitter.js:1:37967)
    at new Parser (/Users/jeffhykin/Nextcloud/Programming/tree-sitter/node_modules/web-tree-sitter/tree-sitter.js:1:46475)
    at func (/Users/jeffhykin/Nextcloud/Programming/tree-sitter/out/test.js:3:18)
    at Object.<anonymous> (/Users/jeffhykin/Nextcloud/Programming/tree-sitter/out/test.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
```

**Comment by jeff-hykin** [comment]
I'm using `web-tree-sitter@0.15.2`, I'm only doing `node $filename` to run the file (no typescript/transpiling/polyfill) and I tried running it from the same directory as the file and from the same directory that contains the `node_modules/`.

**Comment by maxbrunsfeld** [comment]
> This code causes an error

Yeah, that isn't specific to Tree-sitter. When you start a line with a left parenthesis in JavaScript, it is a continuation of the previous line, so that code is equivalent to

```js
const Parser = require("web-tree-sitter")(async () => {})
```

> Causes a different error

Before you call `new Parser()` you need to wait until the `Parser.init()` promise completes. It shows an example of this in [the Setup section](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web#setup) of the README.

**Comment by maxbrunsfeld** [comment]
I should add a better error message if a parser is constructed before the `init` promise has completed.

**Comment by jeff-hykin** [comment]
Ah I should've known about the ()'s
Fixing the order of the init actually solves the original problem as well. 
Thanks for the help!
