### ISSUE TITLE
Is Python 2 a dependency?

### ISSUE THREAD

**Issue by jonhue** [tree-sitter/tree-sitter#385]
I built a tree-sitter grammar and a language package for atom. When I now try to install the language package in atom on a Windows machine, the installation fails with this output:

```
> tree-sitter-quik@0.1.0 install C:\Users\jonas\AppData\Local\Temp\apm-install-dir-11969-12948-ksftd.cxo8os\node_modules\language-quik\node_modules\tree-sitter-quik
> node-gyp rebuild


C:\Users\jonas\AppData\Local\Temp\apm-install-dir-11969-12948-ksftd.cxo8os\node_modules\language-quik\node_modules\tree-sitter-quik>if not defined npm_config_node_gyp (node "C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\jonas\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\jonas\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher 
gyp verb could not find "python". guessing location 
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\jonas\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\jonas\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jonas\\AppData\\Local\\atom\\app-1.38.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jonas\AppData\Local\Temp\apm-install-dir-11969-12948-ksftd.cxo8os\node_modules\language-quik\node_modules\tree-sitter-quik
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\jonas\AppData\Local\Temp\apm-install-dir-11969-12948-ksftd.cxo8os\package.json'
npm WARN apm-install-dir-11969-12948-ksftd.cxo8os No description
npm WARN apm-install-dir-11969-12948-ksftd.cxo8os No repository field.
npm WARN apm-install-dir-11969-12948-ksftd.cxo8os No README data
npm WARN apm-install-dir-11969-12948-ksftd.cxo8os No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-quik@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-quik@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jonas\.atom\.apm\_logs\2019-07-09T16_06_52_478Z-debug.log
```

it says that it was checking for `python2` in my path. This baffles me. AFAIK I'm already using other tree-sitter based language packages, how could this one be any different? Does anyone have an idea what might be going on here?

**Comment by Aerijo** [comment]
It is required for building them with `node-gyp`. What do you mean by “using other tree-sitter packages”? Did you build them too, or just install?

**Comment by jonhue** [comment]
@Aerijo Well, I'm using the default language packages for atom. I didn't build anything, but why am I then required to build something for this language package? 😄

**Comment by Aerijo** [comment]
The default language packages are prebuilt. Some community packages also provide prebuilt binaries, which will be automatically selected if your computer matches one.

This requires setup by the package publisher though, and without it the user will need to build the package (and that requires all the build tool dependencies).

**Comment by jonhue** [comment]
@Aerijo is there some documentation on how to prebuilt and publish them?

**Comment by Aerijo** [comment]
@jonhue Not for Tree-sitter specifically, but
- [This](https://electronjs.org/docs/tutorial/using-native-node-modules) gives an overview of building for Electron
- In particular, [prebuild](https://github.com/prebuild/prebuild) is used for `tree-sitter-ruby` and others. You can look there & the PR's introducing it for how to integrate it with CI. I haven't tried `node-pre-gyp`, but it looks interesting.

**Comment by maxbrunsfeld** [comment]
Closing this out because the Python dependency is related to Node.js modules, not Tree-sitter. @Aerijo provided some good links. Good luck!

**Comment by jonhue** [comment]
Thanks for the hints! I had a look at prebuild and got that working. I also downloaded the built tools to compile directly on my windows machine. But now after I installed the package, I get this error in atom:

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-quik](ssh://git@github.com/quik-lang/language-quik) package 0.1.1


### Stack Trace

Failed to load a language-quik package grammar

```
At A dynamic link library (DLL) initialization routine failed.
\\?\C:\code\quik-lang\test\language-quik\node_modules\tree-sitter-quik\build\Release\tree_sitter_quik_binding.node in C:\Users\jonas\.atom\packages\language-quik\grammars\quik.cson

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\code\quik-lang\test\language-quik\node_modules\tree-sitter-quik\build\Release\tree_sitter_quik_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:146719)
    at Object.<anonymous> (C:/code/quik-lang/test/language-quik/node_modules/tree-sitter-quik/index.js:2:20)
    at Object.<anonymous> (C:/code/quik-lang/test/language-quik/node_modules/tree-sitter-quik/index.js:15:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:1:725913)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:3464439)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:359235)
    at l.readFile (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:359076)
    at ~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:580572
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
  at /packages/language-quik/grammars/quik.cson:1:1
```

Any ideas what might be the reason?
