### ISSUE TITLE
ts_parser_reset() causes segfault when reading captures, nodes of stale tree

### ISSUE THREAD

**Issue by ribru17** [tree-sitter/tree-sitter#4044]
### Problem

Iterating over the captures of a querycursor which references a stale root node of a tree (which has later been `reset()` after running with a timeout) causes a segfault. See https://github.com/neovim/neovim/pull/31631#discussion_r1898103653. Traceback:

```
           PID: 106353 (nvim)
           UID: 1000 (whoami)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Sun 2024-12-22 10:59:58 PST (10min ago)
  Command Line: /home/whoami/neovim/bin/nvim --embed --luamod-dev --clean large_file.lua
    Executable: /home/whoami/neovim/bin/nvim
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/kitty-3051-11.scope
          Unit: user@1000.service
     User Unit: kitty-3051-11.scope
         Slice: user-1000.slice
     Owner UID: 1000 (whoami)
       Boot ID: 824b443d7c1e415298ffd5832121e1f4
    Machine ID: 6541f6ca719247c8b00690cbc51ddae1
      Hostname: laptop
       Storage: /var/lib/systemd/coredump/core.nvim.1000.824b443d7c1e415298ffd5832121e1f4.106353.1734893998000000.zst (present)
  Size on Disk: 8.9M
       Message: Process 106353 (nvim) of user 1000 dumped core.
                
                Module libgcc_s.so.1 without build-id.
                Stack trace of thread 106353:
                #0  0x00005555559faca7 in ts_tree_cursor_parent_node ()
                #1  0x00005555559ee971 in ts_query_cursor.advance ()
                #2  0x00005555559f02e5 in ts_query_cursor_next_capture ()
                #3  0x00005555557b6c57 in querycursor_next_capture (L=0x7ffff7e6b380)
                #4  0x0000555555a24d56 in lj_BC_FUNCC ()
                #5  0x0000555555a10da9 in lua_pcall (L=0x7ffff7e6b380, nargs=<optimized out>, nresults=1, errfunc=<optimized out>) at lj_api.c:1122
                #6  0x00005555557a8ef8 in nlua_pcall (lstate=0x7ffff7e6b380, nargs=4, nresults=1)
                #7  0x00005555557acdc0 in nlua_call_ref_ctx (fast=false, ref=65, name=0x555555aa7b93 "line", args=..., mode=kRetNilBool, arena=0x0, err=0x7fffffffbea0)
                #8  0x00005555557acc7f in nlua_call_ref (ref=65, name=0x555555aa7b93 "line", args=..., mode=kRetNilBool, arena=0x0, err=0x7fffffffbea0)
                #9  0x000055555567b06d in decor_provider_invoke (provider_idx=0, name=0x555555aa7b93 "line", ref=65, args=..., default_true=true)
                #10 0x000055555567bb2e in decor_providers_invoke_line (wp=0x555555c4a820, row=47, has_decor=0x7fffffffc030)
                #11 0x00005555556886ba in win_line (wp=0x555555c4a820, lnum=48, startrow=40, endrow=41, col_rows=0, spv=0x7fffffffd970, foldinfo=...)
                #12 0x0000555555694be3 in win_update (wp=0x555555c4a820)
                #13 0x000055555569011a in update_screen ()
                #14 0x0000555555818b7b in normal_redraw (s=0x7fffffffdb10)
                #15 0x0000555555818dfb in normal_check (state=0x7fffffffdb10)
                #16 0x00005555558f8458 in state_enter (s=0x7fffffffdb10)
                #17 0x00005555558168c2 in normal_enter (cmdwin=false, noexmode=false)
                #18 0x00005555557b9c44 in main (argc=6, argv=0x7fffffffdf18)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/whoami/neovim/bin/nvim...

warning: Can't open file anon_inode:[io_uring] which was expanded to anon_inode:[io_uring] during file-backed mapping note processing
[New LWP 106353]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libthread_db.so.1".
Core was generated by `/home/whoami/neovim/bin/nvim --embed --luamod-dev --clean large_file.lua'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ts_tree_cursor_is_entry_visible (self=0x11d23738, index=14)
    at /home/whoami/Documents/CodeProjects/neovim/.deps/build/src/treesitter/lib/src/tree_cursor.c:26
26	      parent_entry->subtree->ptr->production_id,
�[?2004h�[5 q(gdb) exit
�[?2004l
```

### Steps to reproduce

Apologies that the repro is from the Neovim client. I am still working on reproducing this using the rust bindings. That said the functions here mostly do what you expect; additionally: `:parse()` runs a synchronous parse, `parser._parse()` runs one iteration of a parse with timeout of 3ms.

```lua
local line = 'printf("some text");'
local lines = {}
for i = 1, 2000 do lines[i] = line end
vim.api.nvim_buf_set_lines(0, 0, -1, true, lines)

vim.treesitter.start(0, 'c')
local parser = vim.treesitter.get_parser(0)
local tree = parser:parse(true)[1]
local q = vim.treesitter.query.parse('c', "((identifier) @cap)")
local iter = q:iter_captures(tree:root(), 0)
iter()

for depth = 0, 3 do
  vim.api.nvim_buf_set_text(0, 25 + depth, 4, 25 + depth, 5, {})
  parser._parser:reset()
  parser._parse(parser, true, 3)
end
parser:parse(true)

vim.keymap.set('n', 'a', function()
  for _ = 1, 50 do iter() end
end)
```

### Expected behavior

Tree-sitter should not segfault, and the query cursor should likely just return no new captures (or just the old captures)?

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.24.5

### Operating system/version

NixOS, linux kernel 6.11.0

**Comment by amaanq** [comment]
Yeah, in general reproducers should be made using the C or Rust bindings, and not a 3rd party client like Neovim, as that avoids contributors from having to bring in additional dependencies to debug an issue, so it'd be awesome if you're able to craft one. Also, it would help if you can build Neovim with debug symbols, so we can see line nr information in the traceback, as that will be useful in debugging this as is currently

**Comment by ribru17** [comment]
Thanks a ton @amaanq , I reallly appreciate you taking the time to dig into this. It helped a lot! I think I understand the issue now.
