### ISSUE TITLE
Build Errors on Node.js v12

### ISSUE THREAD

**Issue by curran** [tree-sitter/tree-sitter#409]
After trying to follow the instructions for building WASM languages outlined here https://www.npmjs.com/package/web-tree-sitter#generate-wasm-language-files , I encountered the errors below. I'm on Ubuntu Linux. What am I doing wrong?

Related #408 

```
$ npm install --save-dev tree-sitter-cli tree-sitter-javascript

> tree-sitter-cli@0.15.7 install /home/curran/repos/codearea/test-app/node_modules/tree-sitter-cli
> node install.js

Downloading https://github.com/tree-sitter/tree-sitter/releases/download/0.15.7/tree-sitter-linux-x64.gz

> tree-sitter-javascript@0.15.1 install /home/curran/repos/codearea/test-app/node_modules/tree-sitter-javascript
> node-gyp rebuild

make: Entering directory '/home/curran/repos/codearea/test-app/node_modules/tree-sitter-javascript/build'
  CC(target) Release/obj.target/tree_sitter_javascript_binding/src/parser.o
  CC(target) Release/obj.target/tree_sitter_javascript_binding/src/scanner.o
  CXX(target) Release/obj.target/tree_sitter_javascript_binding/src/binding.o
In file included from ../src/binding.cc:3:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/binding.cc: At global scope:
../src/binding.cc:13:11: error: variable or field ‘Init’ declared void
 void Init(Handle<Object> exports, Handle<Object> module) {
           ^~~~~~
../src/binding.cc:13:11: error: ‘Handle’ was not declared in this scope
../src/binding.cc:13:11: note: suggested alternative: ‘rand_r’
 void Init(Handle<Object> exports, Handle<Object> module) {
           ^~~~~~
           rand_r
../src/binding.cc:13:24: error: expected primary-expression before ‘>’ token
 void Init(Handle<Object> exports, Handle<Object> module) {
                        ^
../src/binding.cc:13:26: error: ‘exports’ was not declared in this scope
 void Init(Handle<Object> exports, Handle<Object> module) {
                          ^~~~~~~
../src/binding.cc:13:35: error: ‘Handle’ was not declared in this scope
 void Init(Handle<Object> exports, Handle<Object> module) {
                                   ^~~~~~
../src/binding.cc:13:35: note: suggested alternative: ‘rand_r’
 void Init(Handle<Object> exports, Handle<Object> module) {
                                   ^~~~~~
                                   rand_r
../src/binding.cc:13:48: error: expected primary-expression before ‘>’ token
 void Init(Handle<Object> exports, Handle<Object> module) {
                                                ^
../src/binding.cc:13:50: error: ‘module’ was not declared in this scope
 void Init(Handle<Object> exports, Handle<Object> module) {
                                                  ^~~~~~
../src/binding.cc:13:50: note: suggested alternative: ‘node’
 void Init(Handle<Object> exports, Handle<Object> module) {
                                                  ^~~~~~
                                                  node
In file included from ../src/binding.cc:2:
../src/binding.cc:26:45: error: ‘Init’ was not declared in this scope
 NODE_MODULE(tree_sitter_javascript_binding, Init)
                                             ^~~~
/home/curran/.node-gyp/12.0.0/include/node/node.h:556:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/binding.cc:26:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(tree_sitter_javascript_binding, Init)
 ^~~~~~~~~~~
../src/binding.cc:26:45: note: suggested alternative:
 NODE_MODULE(tree_sitter_javascript_binding, Init)
                                             ^~~~
/home/curran/.node-gyp/12.0.0/include/node/node.h:556:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/binding.cc:26:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(tree_sitter_javascript_binding, Init)
 ^~~~~~~~~~~
/home/curran/.node-gyp/12.0.0/include/node/node.h:217:18: note:   ‘node::Init’
 NODE_EXTERN void Init(int* argc,
                  ^~~~
In file included from /home/curran/.node-gyp/12.0.0/include/node/node.h:63,
                 from ../src/binding.cc:2:
/home/curran/.node-gyp/12.0.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/curran/.node-gyp/12.0.0/include/node/node_object_wrap.h:84:78:   required from here
/home/curran/.node-gyp/12.0.0/include/node/v8.h:9817:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/curran/.node-gyp/12.0.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/curran/.node-gyp/12.0.0/include/node/v8.h:9817:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
In file included from ../src/binding.cc:3:
../src/binding.cc:11:12: warning: ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::New(Nan::NAN_METHOD_ARGS_TYPE)’ defined but not used [-Wunused-function]
 NAN_METHOD(New) {}
            ^~~
../../nan/nan.h:1566:33: note: in definition of macro ‘NAN_METHOD’
     Nan::NAN_METHOD_RETURN_TYPE name(Nan::NAN_METHOD_ARGS_TYPE info)
                                 ^~~~
make: *** [tree_sitter_javascript_binding.target.mk:113: Release/obj.target/tree_sitter_javascript_binding/src/binding.o] Error 1
make: Leaving directory '/home/curran/repos/codearea/test-app/node_modules/tree-sitter-javascript/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/curran/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 5.0.0-20-generic
gyp ERR! command "/home/curran/.nvm/versions/node/v12.0.0/bin/node" "/home/curran/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/curran/repos/codearea/test-app/node_modules/tree-sitter-javascript
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

**Comment by Aerijo** [comment]
I believe your NodeJS version is too recent; all Handles should be Locals. Trying with 10 might work.

**Comment by curran** [comment]
Thank you @Aerijo I will try that.

**Comment by curran** [comment]
Downgrading to Node 10 did the trick! Renamed this issue to be more precise.

I suppose this workaround might be a good thing to mention in the REAMDE.

I'm not sure what it would take to make the build work on Node v12.

**Comment by curran** [comment]
Hooray!
