### ISSUE TITLE
Permission denied error when exec `tree-sitter build-wasm`

### ISSUE THREAD

**Issue by hackwaly** [tree-sitter/tree-sitter#533]
macOS 10.15.3 (19D76)
tree-sitter 0.16.1 (9f77afcd1ff050855259f83fcf50056ad842a790)
node v12.14.0
Docker version 19.03.5, build 633a0ea

```
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v19.03.5 
```

```
$ npx tree-sitter build-wasm ./node_modules/tree-sitter-cpp


emcc command failed - Traceback (most recent call last):
  File "/emsdk_portable/emscripten/tag-1.39.4/emcc.py", line 3704, in <module>
    sys.exit(run(sys.argv))
  File "/emsdk_portable/emscripten/tag-1.39.4/emcc.py", line 2361, in run
    src = re.sub(shared.JS.memory_initializer_pattern, repl, open(final).read(), count=1)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/emsdk_portable/emscripten/tag-1.39.4/emcc.py", line 2352, in repl
    open(memfile, 'wb').write(bytearray(membytes))
IOError: [Errno 13] Permission denied: 'tree-sitter-cpp.wasm.mem'
```

**Comment by maxbrunsfeld** [comment]
Does the file `tree-sitter-cpp.wasm.mem` still exist? Maybe it got created with the wrong permissions, possibly by running this command with `sudo` previously, but then terminating it while it was still running. Can you ensure that it is gone by running `rm -rf tree-sitter-cpp.wasm.mem`.

From what I can tell, this is a file permission problem, and doesn't specifically have to do with Tree-sitter. Let me know if you find out more.
