### ISSUE TITLE
Failing to compile on rust v1.44

### ISSUE THREAD

**Issue by CSRaghunandan** [tree-sitter/tree-sitter#641]
Please find the error log below:

```
error: failed to run custom build command for `tree-sitter-cli v0.14.5`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installMWA1FE/release/build/tree-sitter-cli-0f72a36c6168aac9/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'assertion failed: repo_path.pop()', /home/csraghunandan/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-cli-0.14.5/build.rs:22:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: std::panicking::begin_panic
  12: build_script_build::main
  13: std::rt::lang_start::{{closure}}
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  16: std::panicking::try
             at src/libstd/panicking.rs:274
  17: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  18: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  19: main
  20: __libc_start_main
  21: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `tree-sitter-cli v0.14.5`, intermediate artifacts can be found at `/tmp/cargo-installMWA1FE`

Caused by:
  build failed
```

**Comment by XVilka** [comment]
Same with Rust nightly

```
[i] ℤ rustc --version                                                                                                                                                                                                              20:08:08 
rustc 1.46.0-nightly (feb3536eb 2020-06-09)
tree-sitter-rust on  master 
[i] ℤ cargo --version                                                                                                                                                                                                              20:09:43 
cargo 1.45.0-nightly (40ebd5220 2020-06-01)
```
```
[i] ℤ RUST_BACKTRACE=full cargo install tree-sitter-cli                                                                                                                                                                            20:07:43 
    Updating crates.io index
  Installing tree-sitter-cli v0.14.5
   Compiling autocfg v1.0.0
   Compiling autocfg v0.1.7
   Compiling rand_core v0.4.2
   Compiling libc v0.2.71
   Compiling memchr v2.3.3
   Compiling semver-parser v0.7.0
   Compiling cc v1.0.54
   Compiling maybe-uninit v2.0.0
   Compiling proc-macro2 v1.0.18
   Compiling lazy_static v1.4.0
   Compiling scopeguard v0.3.3
   Compiling version_check v0.1.5
   Compiling unicode-xid v0.2.0
   Compiling serde v1.0.112
   Compiling byteorder v1.3.4
   Compiling regex-syntax v0.6.18
   Compiling ryu v1.0.5
   Compiling bitflags v1.2.1
   Compiling syn v1.0.31
   Compiling log v0.4.8
   Compiling unicode-width v0.1.7
   Compiling serde_json v1.0.55
   Compiling ansi_term v0.11.0
   Compiling tree-sitter-cli v0.14.5
   Compiling itoa v0.4.6
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling cfg-if v0.1.10
   Compiling smallbitvec v2.5.0
   Compiling difference v2.0.0
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling semver v0.9.0
   Compiling thread_local v1.0.1
   Compiling lock_api v0.1.5
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling indexmap v1.4.0
   Compiling num-rational v0.2.4
   Compiling nom v4.2.3
   Compiling textwrap v0.11.0
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
error: failed to run custom build command for `tree-sitter-cli v0.14.5`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installRMzsB0/release/build/tree-sitter-cli-f243da6816bfa3cd/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'assertion failed: repo_path.pop()', /home/akochkov/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-cli-0.14.5/build.rs:22:13
stack backtrace:
   0:     0x55efe3f265a5 - backtrace::backtrace::libunwind::trace::hc3f32ba24d88242a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55efe3f265a5 - backtrace::backtrace::trace_unsynchronized::h1f075597100358e7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55efe3f265a5 - std::sys_common::backtrace::_print_fmt::h4397782fec59f199
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55efe3f265a5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h39652f0242246c81
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55efe3f43e5c - core::fmt::write::h540ac4a6a1232abc
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55efe3f24353 - std::io::Write::write_fmt::haa03b5883ee9e297
                               at src/libstd/io/mod.rs:1537
   6:     0x55efe3f28a30 - std::sys_common::backtrace::_print::ha6d9bdf9f438acec
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55efe3f28a30 - std::sys_common::backtrace::print::ha1fba17a8e5f6bc7
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55efe3f28a30 - std::panicking::default_hook::{{closure}}::hbf9fcecd42c17d90
                               at src/libstd/panicking.rs:198
   9:     0x55efe3f2877c - std::panicking::default_hook::h39b8550780094336
                               at src/libstd/panicking.rs:218
  10:     0x55efe3f29017 - std::panicking::rust_panic_with_hook::hc8b48ce48004c103
                               at src/libstd/panicking.rs:477
  11:     0x55efe3f1e20e - std::panicking::begin_panic::hbc122343de9df350
  12:     0x55efe3f1d7b0 - build_script_build::main::h40c1f4ce266f22d9
  13:     0x55efe3f1df83 - std::rt::lang_start::{{closure}}::ha5768a2c20248f9c
  14:     0x55efe3f293e8 - std::rt::lang_start_internal::{{closure}}::hcf986077e2da8d6b
                               at src/libstd/rt.rs:52
  15:     0x55efe3f293e8 - std::panicking::try::do_call::h076edd10f2a91969
                               at src/libstd/panicking.rs:297
  16:     0x55efe3f293e8 - std::panicking::try::h54343dd1a9d830aa
                               at src/libstd/panicking.rs:274
  17:     0x55efe3f293e8 - std::panic::catch_unwind::h81799eb8afacafdd
                               at src/libstd/panic.rs:394
  18:     0x55efe3f293e8 - std::rt::lang_start_internal::hf4abd869024c3270
                               at src/libstd/rt.rs:51
  19:     0x55efe3f1df72 - main
  20:     0x7fba37a07042 - __libc_start_main
  21:     0x55efe3f1d21e - _start
  22:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: failed to compile `tree-sitter-cli v0.14.5`, intermediate artifacts can be found at `/tmp/cargo-installRMzsB0`

Caused by:
  build failed
```

**Comment by remexre** [comment]
This looks like it was fixed in https://github.com/tree-sitter/tree-sitter/commit/fa68ef4cea4b72e7431ec09a7ceff020684c1318#diff-fdde30b6637cba6a1156b45c252f3239, but there haven't been any new Cargo releases in the last 2 years...

**Comment by maxbrunsfeld** [comment]
Closing in favor of #610
