### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by bugproof** [tree-sitter/tree-sitter#742]
Any idea what this can mean?

```
c:\Users\Konrad\.vscode\extensions\georgewfraser.vscode-tree-sitter-0.1.25\node_modules\web-tree-sitter\tree-sitter.js:1
(function (exports, require, module, __filename, __dirname) { var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);var r,n,o=[],s=function(e,t){throw t},_=!1,a=!1;_="object"==typeof window,a="function"==typeof importScripts,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n=!_&&!r&&!a;var u,i,l,d,c="";r?(c=a?require("path").dirname(c)+"/":__dirname+"/",u=function(e,t){return l||(l=require("fs")),d||(d=require("path")),e=d.normalize(e),l.readFileSync(e,t?null:"utf8")},i=function(e){var t=u(e,!0);return t.buffer||(t=new Uint8Array(t)),q(t.buffer),t},process.argv.length>1&&process.argv[1].replace(/\\/g,"/"),o=process.argv.slice(2),"undefined"!

[Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Emitted 'error' event on FSWatcher instance at:
	at FSWatcher._handleError (c:\Users\Konrad\.vscode\extensions\ms-vscode.cmake-tools-1.4.2\dist\main.js:7789:10)
	at ReaddirpStream.NodeFsHandler._boundHandleError (c:\Users\Konrad\.vscode\extensions\ms-vscode.cmake-tools-1.4.2\dist\main.js:25690:43)
	at ReaddirpStream.emit (events.js:223:5)
	at emitErrorNT (internal/streams/destroy.js:92:8)
	at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'C:\\DumpStack.log.tmp'
}

```

**Comment by patrickt** [comment]
@bugproof It looks like this comes from the https://github.com/georgewfraser/vscode-tree-sitter project, so this bug is probably best filed there.

**Comment by bugproof** [comment]
@patrickt  yeah just realized, sorry.
