### ISSUE TITLE
Build fails with gcc 11

### ISSUE THREAD

**Issue by agriffis** [tree-sitter/tree-sitter#853]
I have a nightly build of tree-sitter and neovim on Fedora COPR, see https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/builds/

Lately the builds on Rawhide (which will become Fedora 34 in the spring) have started failing, with this error:

<details><summary>Click to see build error</summary>

```
Mock Version: 2.7
ENTER ['do_with_status'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/tree-sitter.spec'], chrootPath='/var/lib/mock/fedora-rawhide-x86_64-1608022300.079413/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7fc90051e910>timeout=0uid=1001gid=135user='mockbuild'nspawn_args=[]unshare_net=TrueprintOutput=True)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/tree-sitter.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'} and shell False
Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1607990400
Wrote: /builddir/build/SRPMS/tree-sitter-0.17.3.0.git.2787.d6a3e4c9-1.fc34.src.rpm
Child return code was: 0
ENTER ['do_with_status'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/tree-sitter.spec'], chrootPath='/var/lib/mock/fedora-rawhide-x86_64-1608022300.079413/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7fc90051e910>timeout=0uid=1001gid=135user='mockbuild'nspawn_args=[]unshare_net=TrueprintOutput=True)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/tree-sitter.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'} and shell False
Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1607990400
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.3ilpkM
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf tree-sitter-0.17.3.0.git.2787.d6a3e4c9
+ /usr/bin/gzip -dc /builddir/build/SOURCES/tree-sitter-0.17.3.0.git.2787.d6a3e4c9.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd tree-sitter-0.17.3.0.git.2787.d6a3e4c9
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.0C8ONM
+ umask 022
+ cd /builddir/build/BUILD
+ cd tree-sitter-0.17.3.0.git.2787.d6a3e4c9
+ /usr/bin/make -O -j2 V=1 VERBOSE=1 PREFIX=/usr LIBDIR=/usr/lib64
cc -O3 -Wall -Wextra -Werror -std=gnu99 -fPIC -Ilib/src -Ilib/include   -c -o lib/src/language.o lib/src/language.c
cc -O3 -Wall -Wextra -Werror -std=gnu99 -fPIC -Ilib/src -Ilib/include   -c -o lib/src/lexer.o lib/src/lexer.c
cc -O3 -Wall -Wextra -Werror -std=gnu99 -fPIC -Ilib/src -Ilib/include   -c -o lib/src/get_changed_ranges.o lib/src/get_changed_ranges.c
cc -O3 -Wall -Wextra -Werror -std=gnu99 -fPIC -Ilib/src -Ilib/include   -c -o lib/src/node.o lib/src/node.c
cc -O3 -Wall -Wextra -Werror -std=gnu99 -fPIC -Ilib/src -Ilib/include   -c -o lib/src/parser.o lib/src/parser.c
cc -O3 -Wall -Wextra -Werror -std=gnu99 -fPIC -Ilib/src -Ilib/include   -c -o lib/src/stack.o lib/src/stack.c
cc -O3 -Wall -Wextra -Werror -std=gnu99 -fPIC -Ilib/src -Ilib/include   -c -o lib/src/query.o lib/src/query.c
cc -O3 -Wall -Wextra -Werror -std=gnu99 -fPIC -Ilib/src -Ilib/include   -c -o lib/src/tree.o lib/src/tree.c
cc -O3 -Wall -Wextra -Werror -std=gnu99 -fPIC -Ilib/src -Ilib/include   -c -o lib/src/subtree.o lib/src/subtree.c
cc -O3 -Wall -Wextra -Werror -std=gnu99 -fPIC -Ilib/src -Ilib/include   -c -o lib/src/tree_cursor.o lib/src/tree_cursor.c
In file included from lib/src/././subtree.h:12,
                 from lib/src/./tree_cursor.h:4,
                 from lib/src/tree_cursor.c:3:
lib/src/tree_cursor.c: In function 'ts_tree_cursor_copy':
lib/src/./././array.h:60:3: error: 'res' is used uninitialized [-Werror=uninitialized]
   60 |   array__splice(                                               \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   61 |     (VoidArray *)(self), array__elem_size(self), (self)->size, \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   62 |     0, count,  contents                                        \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   63 |   )
      |   ~
lib/src/./././array.h:55:3: note: in expansion of macro 'array_extend'
   55 |   array_extend((self), (other)->size, (other)->contents)
      |   ^~~~~~~~~~~~
lib/src/tree_cursor.c:451:3: note: in expansion of macro 'array_push_all'
  451 |   array_push_all(&copy->stack, &cursor->stack);
      |   ^~~~~~~~~~~~~~
lib/src/tree_cursor.c:448:16: note: 'res' declared here
  448 |   TSTreeCursor res = {NULL, NULL, {0, 0}};
      |                ^~~
cc1: all warnings being treated as errors
make: *** [<builtin>: lib/src/tree_cursor.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.0C8ONM (%build)
    Bad exit status from /var/tmp/rpm-tmp.0C8ONM (%build)
RPM build errors:
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.9/site-packages/mockbuild/util.py", line 600, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/tree-sitter.spec

```

</details>

It seems like this error is triggered by a difference between F33 and Rawhide, maybe a different compiler version (the flags are the same, see [here for a successful F33 build](https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-33-x86_64/01832521-tree-sitter/build.log.gz))

But even if that triggers it, my guess is that we need a fix in the tree-sitter code to satisfy the compiler. Any suggestions?

**Comment by agriffis** [comment]
It looks like Fedora 34 is using GCC 11
